addSbtPlugin("org.scala-js" % "sbt-scalajs" % "$scalajs_version$")
addSbtPlugin("org.scala-native" % "sbt-scala-native" % "$scalanative_version$")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject"      % "$sbt_cross_project_version$")
addSbtPlugin("org.portable-scala" % "sbt-scala-native-crossproject" % "$sbt_cross_project_version$")
addSbtPlugin("io.get-coursier" % "sbt-coursier" % "$sbt_coursier_version$")
addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "$scalafmt_version$")